import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { MembersModule } from '../members/members.module';
import { FamiliesModule } from '../families/families.module';
import { SquadsModule } from '../squads/squads.module';
import { SessionsModule } from '../sessions/sessions.module';
import { AttendanceModule } from '../attendance/attendance.module';
import { FinanceModule } from '../finance/finance.module';
import { AwardsModule } from '../awards/awards.module';
import { ApiKey } from './entities/api-key.entity';
import { ApiKeysService } from './api-keys.service';
import { ApiKeysController } from './api-keys.controller';
import { ReadApiController } from './read-api.controller';
import { ApiKeyGuard } from './guards/api-key.guard';
import { ReadOnlyApiGuard } from './guards/read-only.guard';
import { ApiKeyScopesGuard } from './guards/api-key-scopes.guard';

/**
 * Club-scoped read API keys (TEM-32).
 *
 * Holds two controllers with quite different audiences: ApiKeysController is
 * the JWT-authenticated management surface for club admins, and
 * ReadApiController is the published, key-authenticated read surface. They
 * share a module because they share the key lifecycle, and because the
 * OpenAPI document is generated by including exactly this module.
 *
 * The domain modules are imported for their read services only. Nothing here
 * writes to them, and no service from here is exported, so the read API
 * cannot become a back door into the rest of the app.
 */
@Module({
  imports: [
    TypeOrmModule.forFeature([ApiKey]),
    MembersModule,
    FamiliesModule,
    SquadsModule,
    SessionsModule,
    AttendanceModule,
    // Covers both InvoicesService and MandatesService.
    FinanceModule,
    AwardsModule,
  ],
  controllers: [ApiKeysController, ReadApiController],
  providers: [ApiKeysService, ApiKeyGuard, ReadOnlyApiGuard, ApiKeyScopesGuard],
})
export class ApiKeysModule {}
